### ISSUE TITLE
Can't get ExternalModuleDependencies working

### ISSUE THREAD

**Issue by lohals** [OneGet/oneget#164]
When publishing a module to an internal repository, with a RequiredModule set in the psd1 manifest available on PSGallery repository i get  the error: 'PowerShellGet cannot resolve the module dependency '[external module from PSGallery]' of the module '[internalmodule]' on the repository '[internal repository]'. Verify that the dependent module ''[externalmodule]' is available in the repository '[internal repository]'. If this dependent module '[externalmodule]' is managed externally, add it to the ExternalModuleDependencies entry in the PSData section of the module manifest.

So i tried to add it to the PrivateData hashtable in the manifest instead: ExternalModuleDependencies = @(@{ ModuleName='[externalmodule]';ModuleVersion="[version]" ;}).

Now i Can publish the module to my internal repository. However, doing a 
find-package [internalmodule]-IncludeDependencies doens't list the required external module (NB: it works fine with internal required modules).

I tried to manipulate the .nuspec file after having done publish-module, adding the external module to the dependencies section. 

Now find-package [internalmodule]-IncludeDependencies lists the external module as a dependency correctly (including the source Property pointing to https://www.powershellgallery.com/api/v2/), however trying to do install-package [internalmodule] gives the error:
WARNING: Unable to resolve module dependency -- module 'nuget:[externalmodule]/[externalmoduleversion]' not found.

I can't find any documentation online as to how to get ExternalModuleDependencies working. So now i am posting here.

Im using Win8.1 with WMF 5.0 production preview.

**Comment by lboening** [comment]
I have same issue, I believe

**Comment by KirkMunro** [comment]
I don't have time to dig in, but I have used ExternalModuleDependencies with success.  I identify the actual module dependencies (both internal and external) using RequiredModules and NestedModules, and then in ExternalModuleDependencies I simply provide an array of module names (strings), without the versions.  I believe that's the part that is causing issue for you.

Try putting the module requirements (with versions if you need them) in RequiredModules/NestedModules, and then use ExternalModuleDependencies to tell PowerShellGet which of the required modules don't have to be in the repository by identifying them by name and name only.

**Comment by lohals** [comment]
Thanks for the response Kirk! I just tried to implement you suggestion, and got it working. I add the external module likeso:
RequiredModules = @(@{ModuleName = 'psFtp'; ModuleVersion = '1.7'; })
and then add psFtp like so:
PrivateData = @{
        PSData = @{
    # ExternalModuleDependencies
    ExternalModuleDependencies = @('psFtp')
   }
} # End of PrivateData hashtable

One gotcha i was struggling with, was to add to PSData hashtable and not just the root PrivateData Hashtable. That took me som time to realize :)

One limitation though, is that external modules doesn't get installed automatically when installing. You only get a warning that you have to make sure that the external managed module is installed. Could be nice if there was an option to force external module installation (fx. if it exist in Trusted repository)....

**Comment by lohals** [comment]
Though I  still have some trouble. I am using the New-ModuleManifest CmdLet to create the psd1 file, but there is no Parameter for ExternalModuleDependencies. I was adding it like this:
-PrivateData @{ ExternalModuleDependencies=@("psFtp")}

But that doesnt work beacuse, ExternalModuleDependencies is not added nested into the PSData  hashtable but beside it in the PrivateData hashtable, and its not working when publishing. In my previous response i edited the PSD1 file manually afterwards to get publish-module working. 
I cant figure out how to add ExternalModuleDependencies as a Parameter to the New-Modulemanifest cmdlet.

Question: is there no way to add ExternalModuleDependencies when calling  New-Modulemanifest cmdlet, or do we have to manually write it in the psd1?

**Comment by KirkMunro** [comment]
Thanks for responding back with the details about how you got it working.

For your New-ModuleManifest problem, using this syntax should work:

-PrivateData @{ PSData = @{ ExternalModuleDependencies = @('psFtp') } }

For module dependencies, I think having dependencies span repositories would be a bad idea.  There is no hard link between a module and any given repository, and anyone can mirror modules across multiple repositories, and if they have access to do so (if they own the backend repository), they can also remove a module completely from a repository.  Suddenly dependencies may become broken in that scenario, so with that in mind I think a better package management solution would be to mirror the modules you are taking dependencies on into the repository where users will go for your module.  It would be easy to set up a scheduled task, or a runbook in SMA or Azure Automation or something similar to check for updates and then mirror them across to the desired repository, and, at the time someone uses Install-/Update-Module to install or update your module, if a required module in your repository is a version or two behind, that wouldn't matter because of how Install-/Update-Module do version checks.  If the module requires a certain minimum version, and a newer version is installed, it will be happy; otherwise, it will install the version you have in your repository.  If the module requires a specific version, you'll have made sure that version is in your repository.

The only thing I'm unsure about with this type of approach is how well Update-Module deals with module mirroring.  i.e. If a user installs psFtp from the PowerShellGallery, then that module has local metadata in it telling it to use PowerShellGallery when updating.  But let's say they're on version 1.8 of that module (I just picked an arbitrary number), and then they install your module from your repository, and that your module explicitly requires version 1.7.  Suddenly 1.7 gets installed, with metadata in it identifying your repository as the update location.  I have no idea what happens at this point as things move forward, maybe with your module updating the minimum requirement to 1.9 at some point.  If an end user invokes Update-Module, and both repos have 1.9 or later, how does that get resolved?

Suddenly the module has multiple sources of truth and that can get messy, which makes me question my thoughts on mirroring modules.  I still think cross-repo dependencies isn't a great solution though.  Maybe someone from the OneGet/PowerShellGet team can comment on how mirroring is supposed to be handled for PowerShell modules?

**Comment by lohals** [comment]
Unforturnately i cant get setting External module dependencies working. Adding the line
`-PrivateData @{ PSData = @{ ExternalModuleDependencies = @('psFtp')}}`
results in a second PSData property being added, which isn't resolved correctly:
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()
        # A URL to the license for this module.
        # LicenseUri = ''
        # A URL to the main website for this project.
        # ProjectUri = ''
        # A URL to an icon representing this module.
        # IconUri = ''
        # ReleaseNotes of this module
        # ReleaseNotes = ''
    } # End of PSData hashtable
    # PSData
    PSData = 'System.Collections.Hashtable'
} # End of PrivateData hashtable

I explored the System.Management.Automation.dll and noted how the New-Modulmanifest cmdlet processes the PrivateData Hashtable input data. It only processes the -PrivateData hashtable for immediate properties (nested hashtables are not supported), which are added at the same level as PSData property in the PrivateData section of the manifest. The only things that get into the nested PSData hashtable, are the values set by the other properties on New-modulemanifest that should end up i the PSData section (LicencseUri etc.), and there is no ExternalModuleDependencies property.

To my conclusion, this means that  currently ExternalModuleDependencies is not supported in the New-Modulemanifest cmdlet. I don't know if this is on purpose or it is a bug. Maybe it should be reported here https://connect.microsoft.com/PowerShell?


Thank you for your thorough discussion on external modules installation/updating. It seems to me there is isn't  perfect solution to this issue at the time of writing. I am not sure whats right or wrong. Could be nice if it could be handled in the realm of package management/manifest definitions. But yes it would be nice to hear some thoughts on this issue of private module repos with external dependencies.

**Comment by KirkMunro** [comment]
That's a bug.  New-ModuleManifest should support nested hashtables just fine.  They just didn't think of the need for that.  You should file that bug here instead of on Connect:

https://windowsserver.uservoice.com/forums/301869-powershell?query=New-ModuleManifest

I put a query in that link as an example of how you might check to see if the bug is already filed.  You should replace the query text with the actual bug (something like "New-ModuleManifest does not support nested hashtables inside of PrivateData", and then click on the "Post a new idea..." button and provide the details.

The PowerShell Team is using UserVoice for bug tracking now instead of Connect.  Once you've filed it, post a link back here and I'll add my vote.

**Comment by KirkMunro** [comment]
@jianyunt: It would be great to hear from the PowerShellGet team about how mirroring should be used when you are working with modules across multiple repositories.  I'd like to understand what happens when you have a module with multiple versions installed that come from different repositories when you try to update it.  Have you planned for this scenario so that repository owners can mirror content that they require within their repository in order for dependencies to work properly without potentially causing issues when modules are installed from multiple repositories?  See my comments earlier on this thread for an example scenario that I'm concerned about when it comes to content mirroring.

**Comment by lohals** [comment]
I have created a suggestion at the powershell uservoice:

https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/12243096-new-modulemanifest-doesn-t-support-externalmoduled

Please go vote :)

**Comment by jianyunt** [comment]
@KirkMunro there is a hidden file: PSGetModuleInfo.xml under a module\version folder installed by PowerShellGet. it stores info like where the module originally installed from. When update-module, it goes out the same location for the latest.  When update-module,  the most recent one gets updated.

**Comment by KirkMunro** [comment]
@jianyunt Thanks, that's helpful, but I need to clarify something.  Let's say you have versions 1.0 and 1.1 of module M installed, with 1.0 from one repository and 1.1 from another.  When you invoke Update-Module, which of these statements is true:

1) PowerShellGet will only look at the latest version that you have (1.1), and it will check for updates for that module on the repository identified in the hidden PSGetModuleInfo.xml file that is in the M\1.1 folder.

2) PowerShellGet will look at the latest version that you have _for each repository_, will check for updates on each repository to see what the latest version is that is available, and it will update to the latest version it can possibly update to.  In the event that multiple repositories return the latest version, it will update using the repository that has the highest version installed on your system and that returned the latest version.

I think you what you said happens is scenario 1.  I think what needs to happen is scenario 2.

With scenario 1, a module may get "stuck".  For example, consider the following sequence of events:

- Sam installs module A 1.0 from repo A.  Module A 1.0 requires module M 1.0, so module M is installed as well.
- Creator of module M updates it to version 1.1 and publishes it to repo A.
- Someone creates a new repo, publishes module B 1.0 to that repo, as well as a mirrored copy of module M 1.1 because module B is dependent on it.
- Sam installs module B 1.0 from repo B.  Module B 1.0 requires module M 1.1, so it gets installed along with it from repo B.
- Creator of module B goes out of business, decides to leave PowerShell behind forever, changes jobs, moves to Mars etc...basically disappears, and the modules in repo B are left to stagnate online or the repo is taken down forever.
- Creator of module M updates it to version 1.2 and publishes it to repo A.
- Sam invokes Update-Module

At this point, sam has M 1.0 and 1.1 installed from two different repos.  When Update-Module is invoked, if you use scenario 1 then PowerShellGet looks at version 1.1 and checks for an update.  If the repo has disappeared, I presume an error will happen.  But if the repo is left online but stagnant, it will find version 1.1 of M and do nothing.  In both cases version 1.2 of M is available but the end user may never see it with scenario 1, right?

If you use scenario 2 instead though, and identify the latest version of a given module from each repo where it was sourced, check each repo to see if there is an update, identify the latest version, and if it is available from multiple repos, download it from the repo that is associated with the highest version you have on disk, then that would eliminate this possibility and allow mirroring to be performed with less risk of module updates dying on the vine.

Maybe this scenario is overthinking it, but I think mirroring is important, and it is equally important to consider this sequence of events (or similar sequences) to ensure that PowerShellGet can make a best effort to get you the latest version of a module every time you invoke Update-Module.

**Comment by jianyunt** [comment]
Thanks Kirk for your explanation. I still have one question: for the scenario #2, if Sam has M 1.0 and M 1.1 installed from difference repos, when Sam run update-module, both 1.0 and 1.1 will be updated. If Repo A has updated M  to 1.1 but Repo B has no change, e.g. M1.1.  What's outcome do you expect in this case?

**Comment by KirkMunro** [comment]
In that case I would expect nothing to change.  You look at the latest version for each repo, you check to see if there are updates that are not already installed from any repo, and only if that is true then you proceed to update using the latest version possible from the repo with the highest version already installed that contains that update.  With your question, the updater would identify that the 1.1 update is already installed, even if it were to come from another repo, so there is nothing to do.  And if a user wanted to "re-home" a module version, they could Install-Module -Force -RequiredVersion _versionNumber_ -Repository _repoTheyWantItAssociatedWith_.

**Comment by jianyunt** [comment]
I will create a backlog for team to discuss. Thanks again.

**Comment by KirkMunro** [comment]
@bmanikm Are you closing this because @jianyunt created a backlog task for the team to discuss, so there is nothing to do until that comes off the backlog?  Just curious, because I'd like to know what will happen in the mirroring scenarios described above once your team comes to a decision on it.

**Comment by bmanikm** [comment]
Hi @KirkMunro, Here are my thought on mirroring scenarios:

How do you differentiate whether a repository is a mirror of another repository? If many customers need this support we may consider adding additional property on PSRepository saying that the this is a mirror of another repository and use both repositories in finding the updates.

Two different repositories can have modules owned by different users with the same name but their functionality can be different. Update-Module always honors the repository of the latest module version. It is up to the users to manually install the latest version from a different repository. 

In mirroring scenarios, I think, customers should always user the mirrored repository for updates. Since mirrored repositories will have the sync schedule, it should eventually get the latest versions from the source repository.

If mirroring scenario is required for your enterprise scenario, please create a feature request on PowerShell UserVoice.

**Comment by StingyJack** [comment]
@jianyunt - so, will my team be able to use dependencies like VSSetup in our own modules (to find MSBuild for example), or am I left with a crummy import/install module headers or saving a copy external modules and publish them to our in house repo?

**Comment by jianyunt** [comment]
@StingyJack, install-module works for dependences within the same repo. For dependency modules are hosted on the repo different from that module to be installed, I recommend you to publish them to your house repo. If you do not wish to publish them into your house repo, you may save modules to your common file share, Register-PSRepository -Name local -SourceLocation \\server\commonshare,  then install these modules from file share first.

**Comment by StingyJack** [comment]
Thanks for the clear and prompt response on that. I figured the latter was going to be the action needed. I don't have a problem with save-push for them except that it may be forgotten from time to time, and may be able to just configure proget as some kind of connector for them.

Is there a significant reason why this approach for powershellget was chosen instead of the nuget style of cross-repo dependencies?  I wasnt able to pick it out of the conversation above.

**Comment by JustinGrote** [comment]
FYI I came here because I tried ExternalModuleDependencies = 'mydependency' and it turns out you *have* to wrap it in an array, a single string will fail with this message.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@jianyunt, has interrepository dependency management been provided since you commented?
