### ISSUE TITLE
PowerShellGet failed to Publish-Module without FunctionsToExport field

### ISSUE THREAD

**Issue by anpur** [OneGet/oneget#178]
I have a PowerShellGet module which consists of nested modules only.

When we switched to new build machine it publish build started to fail with following error:

    Publish-PSArtifactUtility : The property 'FunctionsToExport' cannot be found on this object. Verify that the property exists.
    At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:853 char:17

After some reverse engineering of `PSModule.psm1` I've found that only way to fix it is to add:

    FunctionsToExport = '*'

to module's definition (`SomeModule.psd1`).

Please, do not hesitate to contact me for any additional information.

**Comment by KirkMunro** [comment]
That's a known issue.

Note that you should define each of the *ToExport attributes in your manifest, and that each attribute should either be an empty array (if nothing is exported -- this may seem redundant but it is necessary for improved performance when loading your module) or an array of the actual items of that type that are exported (this is also necessary for performance during command discovery, so that the discovery engine knows exactly what is exported from the module -- plus, it's a best practice that is worth following).

**Comment by nightroman** [comment]
Interesting. My module has no `*ToExport` fields at all. `Publish-Module` works.

**Comment by KirkMunro** [comment]
Maybe the bug is when you have at least one *ToExport field?  Not sure.  All I know is when I hit the issue I opened the script module and fixed it locally.  I haven't checked, maybe the issue has been fixed and published already, in which case the OP should update their PowerShellGet module.

**Comment by bmanikm** [comment]
This issue was already fixed in the latest PowerShellGet module.

**Comment by war59312** [comment]
Sorry for Off Topic. But...

OneGet Developers, you should label yourself as "OneGet member".

Like Kodi does here:

https://github.com/xbmc/xbmc/pull/9541#issue-145514379

So it's more obvious who is who. ;) Sorry for off topic. Would help.. Thank you.
