### ISSUE TITLE
Import PackageProvider by default

### ISSUE THREAD

**Issue by citelao** [OneGet/oneget#219]
Hey---

I'm trying to save the ChocolateyGet provider to be available for all new Powershell sessions. Right now I have to run `Import-PackageProvider ChocolateyGet` for every new session.

It looks like the `-ForceBootstrap` or `-Force` options might be helpful, but neither of them had an effect.

Is there a way to do this?

**Comment by jianyunt** [comment]
@citelao, I think  you can specify -providername ChocolateyGet for auto-loading it. However you do need to explicitly install it.
 ChocolateyGet is not designed to be bootstrapped. In fact, all providers in the PowerShellgallery.com work in the same way, i.e., not designed for bootstrapping. Yes -ForceBootstrap or -Force will not help.

**Comment by citelao** [comment]
@jianyunt Thanks for the response! 

I'm not sure I understand your concrete advice about `-providername`. `Import-PackageProvider` works as-is, but does not force load for new sessions.

Also, what do you mean by "not designed for bootstrapping"? If bootstrapping is what I think it is (loading at shell startup), why shouldn't they be able to? It seems equivalent to adding a line to my Powershell profile.ps1.

**Comment by jianyunt** [comment]
@citelao, when I say "-providername", I mean that, if you are on Win10 Anniversary, Windows Server 2016, or WMF 5.0 RTM or WMF 5.1 Preview, running the following cmdlet will load the provider by OneGet.
```PowerShell 
find-package -name nodejs -providername ChocolateyGet 
```

The way that provider loading works is similar to module loading. Assuming you have multiple PowerShell modules installed on your system, but not all of them will be loaded when you start a new session. You can find out by get-module. This is mostly for performance consideration.

**Comment by citelao** [comment]
Well that makes sense :D

Who controls what can/can't be autoloaded? How?

**Comment by jianyunt** [comment]
So far, only NuGet provider is auto-loaded by OneGet.  The [NuGetProvider](https://github.com/OneGet/NuGetProvider) is not PowerShell module.  We are internally hosting it in our storage. It follows swidtag [something like this](https://github.com/OneGet/ProviderRegistry/blob/master/nuget.feed.swidtag). This entire publishing NuGet provider process is manual - not convenient. 
We recommend people publish their providers to the PowerShellGallery.  In fact, the latest PackageManagement (aka OneGet) module in the PowerShellGallery.com includes the Nuget provider already, so that a user does not need to fetch (bootstrap) the nuget provider if it does not exist at the very beginning.
