### ISSUE TITLE
Install-Module -Path (?)

### ISSUE THREAD

**Issue by Stephanevg** [OneGet/oneget#367]
Hi guys,

We have a custom repository, where we upload our custom modules. 

Registering the repository, I can influence the location of where the module will be installed via the following command:

```powershell
Install-Module mYCustomModule -Repository MyRepo -Scope AllUsers
```

That will install the module in ```C:\ProgramFiles\WindowsPowerShell\Modules.```

We want to seperate our custom modules from the ones of our clients, and for that, we wanted to have them in a separate folder, let's say ```C:\woop\MyModules``` using ```install-Module```

I couldn't find a -Path on Insstall-Module. 
How can I install my modules in a path that matters to us?

Thanks in advance!

**Comment by JKeithB** [comment]
Please post issues regarding PowerShellGet should be raised in Github.com/powershell/powershellget.
In response to your question:
Take a look at Save-Module, which has a Path option and will copy dependencies. What it will not do is the validation steps (eg: test-modulemanifest & validating signatures) that are done by Install-Module. With your scenario, that doesn't look like a problem. 
Install-Module doesn't have a path option, because we put the items in well-known locations where we can guarantee they will work. The purpose of Install-Module is to ensure that, when it finishes, the next command run by that user can be a cmdlet in the module that was placed on the box.
