### ISSUE TITLE
How does PackageManagement work (it is not an issue,but makes me confuse)

### ISSUE THREAD

**Issue by tlsalex** [OneGet/oneget#402]
what is not clear to me : PowerShell Package Management - Repository vs Provider vs Source

I am trying to understand package management in PowerShell, and I am getting an incomplete picture. When I look at the objects PSRepository, PackageProvider, and PackageSource, they all seem to have the following relationships:

A PSRepository can provide zero or more PowerShell modules. A PSRepository must have one, and only one, PackageProvider. An example of a repository is PSGallery.
A PackageProvider can serve zero or more PSRepository objects. A PackageProvider must have one or more PackageSource objects. A PackageProvider is sometimes referred to as a "Package Manager". Some examples of package providers include NuGet, Chocolatey, or PowerShellGet.
A PackageSource must serve one and only one PackageProvider. Some examples of package sources include nuget.org, MyCustomVSTSFeed, or PSGallery.

I've looked at the following links, but it still doesn't provide a clear picture of how they are related.

about_PackageManagement
psgallery_gettingstarted

Why does a PSRepository have a property called PackageManagementProvider of type string instead of type PackageProvider?
Why does a PSRepository have its own SourceLocation property, if it already has a source reference through its provider?
Why is PSGallery both a PackageSource and a PSRepository?
Why is PowerShellGet both the name of a module that provides access to the gallery, and the name of a PackageProvider?

**Comment by edyoung** [comment]
PackageManagement is a generic system for installing many kinds of packages. PowerShellGet is specifically for installing PowerShell items (modules, scripts and DSC resources). 

In PackageManagement, a PackageProvider is something which manages a particular *kind* of package, for example Nuget or Chocolatey. A PackageSource is a particular site which contains packages. So Nuget is a PackageProvider, and Nuget.org or your own internal Nuget feed could be registered as  PackageSources.

PowerShellGet extends PackageManagement in two ways. First, it's a layer "on top" of PackageManagement which understands PowerShell concepts like Modules and Scripts. So Install-Module will call PackageManagement's Install-Package command under the hood. Second, PowerShellGet implements a PackageProvider which PackageManagement calls in order to manage PowerShell Modules. 

A PSRepository is PowerShellGet's term for a PackageSource which contains PowerShell modules or scripts, but it's the same thing as a PackageSource. Register-PSRepository wraps Register-PackageSource, so after you register the PSGallery you see it listed as both a PackageSource and a PSRepository.

So:

*Why does a PSRepository have a property called PackageManagementProvider of type string instead of type PackageProvider?*

Not sure, but you can just ignore the property in practice.

*Why does a PSRepository have its own SourceLocation property, if it already has a source reference through its provider?*

A Provider doesn't specify a SourceLocation, but a PSRepository and a PackageSource both do. 

*Why is PSGallery both a PackageSource and a PSRepository?*

See above. All PSRepositories are PackageSources, and all PackageSources with Provider PowerShellGet are PSRepositories. They are 2 different views of the same object.

*Why is PowerShellGet both the name of a module that provides access to the gallery, and the name of a PackageProvider?*

See above. They are the two ways that PowerShellGet extends the generic PackageManagement framework to make it work better for PowerShell specifically.

**Comment by tlsalex** [comment]
![why](https://user-images.githubusercontent.com/36788337/48592240-64be1800-e982-11e8-8a4e-11a235f959e1.PNG)
![installation](https://user-images.githubusercontent.com/36788337/48594401-588a8880-e98b-11e8-9e69-253859cfe3d1.PNG)


Hey @edyoung ,
Thank you ,now I understand the relationship between PSrepository and package source. but I still not quite clear for this case. I want to know the process when install a package. Is it like this ? when I run install-package -name treesize , package management system will choose a ps-repository which has a package source associate with it ,  like PSGallery , to search treesize package, and then the associated package source use a package provider which associated with it to install the package. It is like that ,

I found PSrepository has a package source associate with it.
I found Package source has a package provider associate with .
But there is no PSrepository or package source associate with package provider(provider just some technology to install or manage package ?).

If package management system try to find or install a package from package provider , how can it find the specific package , it does not have a psrepository or source associate with it.

How ever the real installation process with use a package provider to find or install a package , just these 2 installation process show in attached ,

So could you please explain the installation process according the attached cases (it involves two provider , which is powershellget and PackageManagement Provider 'NuGet' which make me more confuse , but to know the whole process when install a package is more important to me ).

**Comment by edyoung** [comment]
I think my explanation above already answers most of the questions you have about the relationship between PSRepository, PackageSource and PackageProvider. Please take another look.

To cover the overall flow:

When you run Install-Package Treesize, PackageManagement enumerates all the PackageSources you have registered. For each of those, it loads the PackageProvider for that source, and then asks the provider 'do you have a package matching treesize'? Each package provider then searches for a corresponding package in the relevant source. Package Management enumerates the result and calls back into the PackageProvider to install the matching package.

The PowerShellGet PackageProvider is special. Since the PowerShell Gallery is actually a NuGet feed, it internally uses the Nuget PackageProvider to do most of the work. So when PackageManagement asks the PowerShellGet provider 'do you have a module called treesize?' it makes a query to the Nuget PackageProvider to actually query the module source, then returns the results to the user. Most of the time this is an implementation detail that only matters if you want to change the PowerShellGet or PackageManagement code.
