### ISSUE TITLE
CI testing for coreclr is not testing against RTM version of PowerShell Core but 6.0.0-beta.5 and 6.0.0.14-alpha.14 and other build/test problems

### ISSUE THREAD

**Issue by bergmeister** [OneGet/oneget#415]
CI testing for coreclr is performed against old version of pscore.
The old whole build system has not been maintained at all in the last years, leading to a big pile of debt that makes it difficult to move anything forward due to inter dependencies:
- 'Legacy' tests need to be removed (by legacy the code refers to the old `6.0.0.14` alpha version of PSCore
- Pester needs to be bootstrapped now since it is not included in PowerShell any more
- The PowerShellGet submodule needs to be removed since PSCore now ships with it.
- The build image should be updated from `WMF5` to `Visual Studio 2017` for AppVeyor, which contains PSCore 6.1 already out of the box, I am sure similar thoughts apply to Travis
- This expression [here](https://github.com/OneGet/oneget/blob/WIP/src/Microsoft.PowerShell.PackageManagement/PackageManagement.psm1#L13) is true for PSCore RTM, meaning it actually uses the `netcoreapp2.0` assemblies when it actually could use netstandard1.6 (netcoreapp2.0 is not supported anymore). Just updating this by itself requires the update of the version of PSCore under test since the old versions of PSCore do not support .Net Standard. After updating the PowerShell version to an RTM version it seems that using .net standard does not work at all at runtime
- Pester tests use the old v3 syntax although the latest version of Pester gets installed (v4.*). Although it still works, it is not recommended to use the old syntax.

In order to resolve this, we will need to make one big breaking change in the build and test system. I will open a PR to update the version of PowerShell Core being used soon.

**Comment by alerickson** [comment]
*  'Legacy' tests need to be removed (by legacy the code refers to the old 6.0.0.14 alpha version of PSCore
     **This is actually a Nano Server specific test, hence the use of that particular version of PSCore.  As we move to netstandard2.0 we should certainly update this as well.**

 * Pester needs to be bootstrapped now since it is not included in PowerShell any more
     **That change sounds good to me.**

 * The PowerShellGet submodule needs to be removed since PSCore now ships with it.
     **I would love to remove this submodule, let me see if there's any reason why we'd need to consider keeping it.** 

* The build image should be updated from WMF5 to Visual Studio 2017 for AppVeyor, which contains PSCore 6.1 already out of the box, I am sure similar thoughts apply to Travis
   **There are actually 4 images already on AppVeyor, WMF4, WMF5, and Visual Studio 2017 (for PowerShell Core and Desktop edition).**

* This expression here is true for PSCore RTM, meaning it actually uses the netcoreapp2.0 assemblies when it actually could use netstandard1.6 (netcoreapp2.0 is not supported anymore). Just updating this by itself requires the update of the version of PSCore under test since the old versions of PSCore do not support .Net Standard. After updating the PowerShell version to an RTM version it seems that using .net standard does not work at all at runtime
     **We should change to using the latest RTM of PowerShell, though I'm not quite sure what the nuance is of .net standard not working at runtime.  What exactly is happening when you say it does not work at all at runtime?**

* Pester tests use the old v3 syntax although the latest version of Pester gets installed (v4.*). Although it still works, it is not recommended to use the old syntax.
     **I agree, it would be nice to have the test syntax updated.**

**Comment by bergmeister** [comment]
@alerickson Thanks, I am glad that you agree, PR #416 fixes most of the points
What I meant by  'netstandard is not working' is that 80% of the tests would fail if I made the code use the netstandard binaries in the main psm1 file (I did an experiment in another one of my branches)
