### ISSUE TITLE
Is OneGet dead?

### ISSUE THREAD

**Issue by soroshsabz** [OneGet/oneget#505]
ITNOA

Hi,

Why more than one year that this repo does not any activity? is OneGet dead? or is any other place for development?

thanks

**Comment by ethanbergstrom** [comment]
OneGet, as a framework and API to interact with underlying package managers with PowerShell, is considered 'stable'. There hasn't been much development on it because there hasn't needed to be. 

As far as OneGet-compatible package providers are concerned, I still maintain the 'ChocolateyGet' package provider, which uses Chocolatey as it's underlying package manager, and the 'WinGet' package provider for Windows Package Management. 

Your mileage may vary, depending on the underlying package manager you're interested in using.

**Comment by soroshsabz** [comment]
Thanks for response, Did you can help me to know how to use `WinGet` as package provider with OneGet cmdlet?

Because you answer my first question in title, I close this issue. but I am happy to know how to use `WinGet` as package provider with OneGet cmdlet?

**Comment by ethanbergstrom** [comment]
Hey @soroshsabz 

Check out the readme at https://github.com/ethanbergstrom/winget for examples in how to use the WinGet provider.

**Comment by soroshsabz** [comment]
@ethanbergstrom  What is difference between OneGet and PSResource?
