### ISSUE TITLE
(Win 10) Execution policy for chocolatey packages

### ISSUE THREAD

**Issue by Mike43110** [OneGet/oneget#97]
With the new release of Windows 10 trying to install a chocolatey package fails with the package supposedly being installed while just the powershell script is being downloaded.

Fixing this requires the execution policy to be changed, a simple fix but confusing for a new user.

**Comment by BiTinerary** [comment]
Admittedly, I have no experience with Windows 10. Maybe it's a "simple" fix, maybe not. That all depends on the execution policy changes that have been made. It is afterall supposed to be an entire OS overhaul.

However I doubt that since, Windows hasn't changed much at all (aside from user interface) since it's Windows XP days. On a side note, are very many "new" users going to be using Chocolately? I just thought that was kinda funny.

At any rate there's another program out there called OneGet, perhaps they have a working alternative solution? Good luck. I'm sure in time Chocolatey will have a working Windows 10 version. I apprecite the input.

**Comment by fearthecowboy** [comment]
HMM.

Thanks for pointing this out; I gotta see if I can prioritize a fix for this asap. This was definitely not the right setting here.

**Comment by atomic1fire** [comment]
@Bitinerary [Chocolatey](https://chocolatey.org/) is going to be a software provider for oneget, and it's already a working package manager so it's inclusion with oneget is a good thing. There's already a working implementation but as @Mike43110 mentioned the script execution settings in one get break chocolatey for some reason.

**Comment by Mike43110** [comment]
While I am at it, is there any way to not have a failed chocolatey install be marked as installed?

It is quite annoying that when my connection is spotty and I install a package which fails to download I have to 1st uninstall the package and  reinstall it.

**Comment by JVimes** [comment]
This is _very_ confusing and time consuming for the user. Two possible options:
- Don't swallow PowerShell's error ("...cannot be loaded because running scripts is disabled on this system. For more information...").
- Run the script in a new instance of powershell.exe with its `-ExecutionPolicy Bypass` flag. Inside that instance scripts can run.

**Comment by jianyunt** [comment]
The Chocolatey provider under OneGet project is only a prototype as a proof of concept and Microsoft internal team does not maintain it. Please send your chocolatey provider request directly to the community, in this case, Rob Reynolds is developing the chocolatey provider: https://github.com/chocolatey/chocolatey-oneget.
