### ISSUE TITLE
MsiProvider should not copy DTF source

### ISSUE THREAD

**Issue by heaths** [OneGet/oneget#98]
While looking into the `MsiProvider` I noticed a copy of the Deployment Technology Framework as source. Why not take a binary dependency on this? It changes very rarely (I think I was the last to touch it ages ago) and @robmen is looking into shipping it as NuGet packages. At the very least, I would think taking a binary dependency would be better than forking the source with no channel back to the original for source updates.

**Comment by fearthecowboy** [comment]
My original desire was to do that, but I have a couple of shorter-term issues that force me to do it the other way.

Since the MSI provider needs to ship in-box, I need (for the immediate term) to only have contributions that are done by MS employees (I have to jump thru more hoops to allow external contributions to anything that ships in-box). My plan was to do that after we ship Windows 10, since I was time constrained when lining up all my approvals to do all this.

So, I grabbed the source for the DTF that I'm using from an internal location, and figured that once I've gone thru that, I'll gladly switch to using a common package. 

Anyway, like you said, it doesn't exactly change very often...

**Comment by heaths** [comment]
Cleaning up old issues. This seems minor, though it does create duplicate code.
